#this is used by the @Value annotation. Use "${property.name}" to access these properties in your code.
spring.application.name=app 

#DATABASE STUFF
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=testdev
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Used for the email service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gymbuddy.official.app@gmail.com
spring.mail.password=zruo spgf hfhx xjzb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true