#this is used by the @Value annotation. Use "${property.name}" to access these properties in your code.
spring.application.name=app 

#DATABASE STUFF
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=testdev
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Disable default security login page
spring.security.filter.dispatcher-types=async,error,request

# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false