#this is used by the @Value annotation. Use "${property.name}" to access these properties in your code.
spring.application.name=app 

#DATABASE STUFF
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=testdev
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect